version: '3'

services:
    db:
        image: custom_mysql
        build: 
            context: .docker/db
            args:
                DB_DATABASE: $DB_DATABASE 
                DB_USER: $DB_USER
                DB_PASSWORD: $DB_PASSWORD
        environment:
            MYSQL_ROOT_PASSWORD: $DB_PASSWORD
        ports:
            - 3306:3306
        command: --init-file=/docker-entrypoint-initdb.d/init.sql
        networks:
            - hanna-web
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: $DB_PASSWORD
        ports:
            - 8080:80
        networks:
            - hanna-web
    queue:
        image: redis:6.2-alpine
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS}
        volumes: 
            - queue:/data
    mailhog:
        image: mailhog/mailhog:latest
        restart: always
        ports:
        - 1025:1025
        - 8025:8025
    localstack:
        image: localstack/localstack
        container_name: localstack
        environment:
            SERVICES: secretsmanager
            DEBUG: 1
            DATA_DIR: /tmp/localstack/data
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        ports:
            - "127.0.0.1:4510-4530:4510-4530"
            - "127.0.0.1:4566:4566"
            - "127.0.0.1:4571:4571"
        volumes:
            - ./data:/tmp/localstack/data
networks:
    hanna-web:

volumes:
    mysql_data:
    queue:
