import { SeedProtocol } from '../protocols/seed.protocol'
import { Injectable } from '@nestjs/common'
import { Connection } from 'typeorm'
import { Breed } from '../../entities/breed/breed.entity'

@Injectable()
export class AddBreedsSeedService implements SeedProtocol<Connection> {
  async seed(connection: Connection) {
    const breedRepository = connection.getRepository(Breed)
    const totalBreeds = await breedRepository.count()
    if (totalBreeds === 0) {
      await breedRepository.save(
        [
          { name: 'Não definido' },
          { name: 'Afegão Hound' },
          { name: 'Affenpinscher' },
          { name: 'Airedale Terrier' },
          { name: 'Akita' },
          { name: 'American Staffordshire Terrier' },
          { name: 'Basenji' },
          { name: 'Basset Hound' },
          { name: 'Beagle' },
          { name: 'Beagle Harrier' },
          { name: 'Bearded Collie' },
          { name: 'Bedlington Terrier' },
          { name: 'Bichon Frisé' },
          { name: 'Bloodhound' },
          { name: 'Bobtail' },
          { name: 'Boiadeiro Australiano' },
          { name: 'Boiadeiro Bernês' },
          { name: 'Border Collie' },
          { name: 'Border Terrier' },
          { name: 'Borzoi' },
          { name: 'Boston Terrier' },
          { name: 'Boxer' },
          { name: 'Buldogue Francês' },
          { name: 'Buldogue Inglês' },
          { name: 'Bull Terrier' },
          { name: 'Bulmastife' },
          { name: 'Cairn Terrier' },
          { name: 'Cane Corso' },
          { name: 'Cão de Água Português' },
          { name: 'Cão de Crista Chinês' },
          { name: 'Cavalier King Charles Spaniel' },
          { name: 'Chesapeake Bay Retriever' },
          { name: 'Chihuahua' },
          { name: 'Chow Chow' },
          { name: 'Cocker Spaniel Americano' },
          { name: 'Cocker Spaniel Inglês' },
          { name: 'Collie' },
          { name: 'Coton de Tuléar' },
          { name: 'Dachshund' },
          { name: 'Dálmata' },
          { name: 'Dandie Dinmont Terrier' },
          { name: 'Dobermann' },
          { name: 'Dogo Argentino' },
          { name: 'Dogue Alemão' },
          { name: 'Fila Brasileiro' },
          { name: 'Fox Terrier (Pelo Duro e Pelo Liso)' },
          { name: 'Foxhound Inglês' },
          { name: 'Galgo Escocês' },
          { name: 'Galgo Irlandês' },
          { name: 'Golden Retriever' },
          { name: 'Grande Boiadeiro Suiço' },
          { name: 'Greyhound' },
          { name: 'Grifo da Bélgica' },
          { name: 'Husky Siberiano' },
          { name: 'Jack Russell Terrier' },
          { name: 'King Charles' },
          { name: 'Komondor' },
          { name: 'Labradoodle' },
          { name: 'Labrador Retriever' },
          { name: 'Lakeland Terrier' },
          { name: 'Leonberger' },
          { name: 'Lhasa Apso' },
          { name: 'Lulu da Pomerânia' },
          { name: 'Malamute do Alasca' },
          { name: 'Maltês' },
          { name: 'Mastife' },
          { name: 'Mastim Napolitano' },
          { name: 'Mastim Tibetano' },
          { name: 'Norfolk Terrier' },
          { name: 'Norwich Terrier' },
          { name: 'Papillon' },
          { name: 'Pastor Alemão' },
          { name: 'Pastor Australiano' },
          { name: 'Pinscher Miniatura' },
          { name: 'Poodle' },
          { name: 'Pug' },
          { name: 'Rottweiler' },
          { name: 'ShihTzu' },
          { name: 'Silky Terrier' },
          { name: 'Skye Terrier' },
          { name: 'Staffordshire Bull Terrier' },
          { name: 'Terra Nova' },
          { name: 'Terrier Escocês' },
          { name: 'Tosa' },
          { name: 'Weimaraner' },
          { name: 'Welsh Corgi (Cardigan)' },
          { name: 'Welsh Corgi (Pembroke)' },
          { name: 'West Highland White Terrier' },
          { name: 'Whippet' },
          { name: 'Xoloitzcuintli' },
          { name: 'Yorkshire Terrier' }
        ]      
      )
    }
  }
}
