name: Test Hanna

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.6
        ports:
          - 3000:3000
        options: --privileged

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Tests in Docker Container
        run: |
          npm run test:ci:docker
